### ISSUE TITLE
order by

### ISSUE THREAD

**Issue by jmarenas** [chicagocomputerclasses/SUPERSQL-Google-Sheets-Function#1]
Hello 
Great work there, very impressive
but, there seems to be an issue with datatypes I think, 
when I try to execute the query bellow with an 'order by'
instruction, the order seems to take place over a string
datatype and not a number (int or decimal), so the order 
over a number field looks like 1, 10, 100, 101 ...
Is there a way to tell the datatypes of each field for a table?

The query:
```
=SUPERSQL("Select distinct p.dex, p.pokemonid 
from ? as p 
where (p.form like '%_NORMAL' or p.form = 'NORMAL') and p.dex <= 151 
order by p.dex";
pokemon!B:X)
```

The results:

dex | pokemonid
-- | --
1 | BULBASAUR
10 | CATERPIE
100 | VOLTORB
101 | ELECTRODE
102 | EXEGGCUTE
103 | EXEGGUTOR
104 | CUBONE
105 | MAROWAK
106 | HITMONLEE
107 | HITMONCHAN
108 | LICKITUNG
109 | KOFFING
11 | METAPOD
110 | WEEZING
---

**Comment by chicagocomputerclasses** [comment]
Could you share an example google sheet?
I've tried to copy paste the same table to google sheets and did order by statement and it seems to work fine.

**Comment by jmarenas** [comment]
This is the spreadsheet I'm working
[Link](https://docs.google.com/spreadsheets/d/1sBzZP6TRTjjjMC7OyZZhY-ApcOX2kCfMxjClB3_azmc/edit?usp=sharing)

**Comment by chicagocomputerclasses** [comment]
You are having this issue because your dex column in your data is text, not a number. SUBSTITUTE function returns text. You should be able to fix this issue by replacing your formula with something like this =arrayformula(iferror(SUBSTITUTE(SPLIT(A1:A;",");".";",")+0;SUBSTITUTE(SPLIT(A1:A;",");".";",")))

**Comment by jmarenas** [comment]
Thanks!! it works.
