### ISSUE TITLE
Keep getting an error

### ISSUE THREAD

**Issue by spicerackk** [chicagocomputerclasses/SUPERSQL-Google-Sheets-Function#4]
Have installed according to your video, and keep getting the below error:

```SyntaxError: Parse error on line 1: SELECT l.Store Name, l.PhG Na ---------^ Expecting 'LITERAL', 'BRALITERAL', 'VALUE', 'STAR', got 'STORE' (line 2211).```

I have two tabs, named Telstra and JB, calling Telstra 'l' like in your video example, and JB is r. Telstra A1 is Store Name, so I am doing ```=SUPERSQL("SELECT l.Store Name, r.Store FROM ? l LEFT JOIN ? r ON l.Store Name = r.Store",Telstra!A1:H,JB!A1:H)``` And get the above error. 

Not sure what I am doing wrong.

**Comment by chicagocomputerclasses** [comment]
Most likely because of the space in column name. Try to wrap the column name in square brackets and see if that helps [Store Name]

**Comment by spicerackk** [comment]
ohhh yeah ok will do, thank you!

**Comment by spicerackk** [comment]
Ok, so tried the above, still errored. If I add the square brackets to both (like this: ```=SUPERSQL("SELECT l.Store Name, r.Store FROM ? l LEFT JOIN ? r ON l.Store Name = r.Store",Telstra!A1:H,JB!A1:H)```) then it only gives me Store Name in A1, and Store in B1, with no other data below it.

**Comment by spicerackk** [comment]
Ok, so what is happening now is with the formula as ```=SUPERSQL("SELECT tl.*, jb.* FROM ? tl LEFT JOIN ? jb ON jb.[Store] = tl.[Store Name]",Telstra!A1:H,JB!A1:H)```, it is now bringing across all data, but not joining the two store lists, but actually adding all of the columns from Telstra, then all the columns from JB next to them, and the total number of rows is 26719 when both sheets total rows equals 331. Not too sure why it is misbehaving.

**Comment by chicagocomputerclasses** [comment]
I'm not sure. Please, share a sample google sheet.

**Comment by spicerackk** [comment]
https://docs.google.com/spreadsheets/d/1Er3ZpS5Nc09H88CINMcGZAcPcy3CgUmUk3p-cOWV7H0/edit?usp=sharing

I am working in the PhGs tab to try and get both lists consolidated, as currently if I try to index/match for JB Tamworth, it pulls the first data for all 3 entries when I need it to show 3 unique entries

**Comment by chicagocomputerclasses** [comment]
So the main problem was that you were selecting the range from A:H and you didn't have data in columns F, G, H. So I switched to A:E and it seems to work fine. That being said, your store names don't match, so you'll need to clean your data before you do this join.

**Comment by spicerackk** [comment]
So maybe I have misunderstood how to use the function properly. I need to get the following data combined into one sheet:

From Telstra:
- Store Name
- PhG Name

From JB:
- Store Name
- PhG Name

After that, I need to be able to display a list of stores that have a PhG but only from the stores that have Andrew Spice as a rep. 
If I use Index/Match, it will find 3 entries for one store (example, JB Tamworth), but only display the first row found for all 3 rows instead of displaying 3 unique entries.

**Comment by chicagocomputerclasses** [comment]
You don't need this function for it. Watch this video https://youtu.be/q8awNSYNdq4
