### ISSUE TITLE
Getting an error with 'filter' on line 63 of code

### ISSUE THREAD

**Issue by epete7** [chicagocomputerclasses/SUPERSQL-Google-Sheets-Function#5]
Says 'TypeError': Cannot read property 'filter' of undefined (line 63, file "supersql"). Any advice on how I can fix this? Came up during debugging because I still just get #NAME error when trying to use. Thanks for any help!

**Comment by chicagocomputerclasses** [comment]
Make sure you are under new V8 runtime.
